=== ASJAYSWAL01/IT-Workshop-Basics/PR_17/student.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (enrollment, name, mobile, email)>
<!ELEMENT enrollment (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== ASJAYSWAL01/IT-Workshop-Basics/PR_17/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "student.dtd">
<?xml-stylesheet type="text/css" href="student.css"?>
<students>
    <student>
        <enrollment>D2D-BE-CE-48</enrollment>
        <name>Ashish Jayswal</name>
        <mobile>7283881430</mobile>
        <email>ashishjayswal698@gmail.com</email>
    </student>
    <student>
        <enrollment>D2D-BE-CE-47</enrollment>
        <name>Hrishit Patel</name>
        <mobile>9998722507</mobile>
        <email>hrishitpatel25206@gmail.com</email>
    </student>
</students>
